#pragma once
#include "AEConfig.h"
#include "entry.h"
#include "AE_Effect.h"
#include "AE_EffectCB.h"
#include "AE_Macros.h"
#include "Param_Utils.h"
#include "AE_EffectCBSuites.h"
#include "AE_GeneralPlug.h"
#include "AEFX_SuiteHelper.h"
#include "AEGP_SuiteHandler.h"

// v3 IDENTITY
#define TRACKERLABS_MATCH_NAME "TrackerLabs_v3_Restore"
#define TRACKERLABS_DISPLAY_NAME "Tracker Labs"

enum {
    TRACKERLABS_INPUT_PARAMS = 0,
    TRACKERLABS_MASTER_INTENSITY, // 1 (Standard 0-100)
    // [NO RANDOMNESS]
    TRACKERLABS_TOPIC_TRACKING,
    TRACKERLABS_TARGET_COLOR,
    TRACKERLABS_TOLERANCE,
    TRACKERLABS_MIN_BLOB_SIZE,
    TRACKERLABS_MAX_OBJECTS,
    TRACKERLABS_TRACKING_SPEED,
    TRACKERLABS_TOPIC_TRACKING_END,
    TRACKERLABS_TOPIC_CONNECTIONS,
    TRACKERLABS_LINES_ENABLED,
    TRACKERLABS_CONN_TYPE,
    TRACKERLABS_MAX_DIST,
    TRACKERLABS_MAX_CONNECTIONS,
    TRACKERLABS_CONN_CHANCE,
    TRACKERLABS_TOPIC_CONNECTIONS_END,
    TRACKERLABS_TOPIC_VISUALS,
    TRACKERLABS_TRITONE_ENABLED,
    TRACKERLABS_COLOR_2,
    TRACKERLABS_COLOR_3,
    TRACKERLABS_LINE_WIDTH,
    TRACKERLABS_LINE_COLOR,
    TRACKERLABS_LINE_CURVATURE,
    TRACKERLABS_FADE_DIST,
    TRACKERLABS_NODE_SIZE,
    TRACKERLABS_NODE_COLOR,
    TRACKERLABS_NODE_SHAPE,
    TRACKERLABS_FILL_OPACITY,
    TRACKERLABS_BOX_PADDING,
    TRACKERLABS_UNIFORM_BOX,
    TRACKERLABS_TARGET_SIZE,
    TRACKERLABS_LABEL_DENSITY,
    TRACKERLABS_LABEL_CONTENT,
    TRACKERLABS_SHOW_LABELS,
    TRACKERLABS_TEXT_SIZE,
    TRACKERLABS_TEXT_COLOR,
    TRACKERLABS_INVERT_FILL,     // New: percentage of boxes with inverted video inside
    TRACKERLABS_TOPIC_VISUALS_END,
    TRACKERLABS_LICENSE,
    TRACKERLABS_NUM_PARAMS
};

extern "C" DllExport PF_Err EffectMain(PF_Cmd cmd, PF_InData* in_data, PF_OutData* out_data, PF_ParamDef* params[], PF_LayerDef* output, void* extra);
